language: node_js
node_js:
  - "10"
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
  - npm run test
after_success:
  - npm run coveralls

notifications:
  email:
    recipients:
      - nick121212@126.com
    on_success: change
    on_failure: always.